// entire code is generated by AI propmting inside VS Code
// for understanding how AI code generation works,
// ignoring type errors in this file by using @ts-ignore directive before the lines that may cause type errors.
// so can ignore type errors for demonstration purposes

console.log("Hello, TypeScript!");

// customer array
const customers = [
  {
    name: "John Doe",
    email: "john@gmail.com",
  },
  {
    name: "Jane Doe",
    email: "jane@gmail.com",
  },
];

// iterate over customers and print their names and emails using for of loop
for (const customer of customers) {
  console.log(`Name: ${customer.name}, Email: ${customer.email}`);
}

//iterate over customers and print their names and emails using forEach loop
customers.forEach((customer) => {
  console.log(`Name: ${customer.name}, Email: ${customer.email}`);
});

// iterate over customers and print their names and emails using for in loop
for (const index in customers) {
  console.log(customers[index]);
}

// seperator
console.log("--------------------------------------------------");

// simple function
// @ts-ignore
function add(a, b) {
  return a + b;
}

console.log(add(5, 10)); // 15
console.log(add("Hello, ", "TypeScript!")); // Hello, TypeScript!
console.log(add(5, "10")); // 510

// seperator
console.log("--------------------------------------------------");

// function with type annotations
function multiply(a: number, b: number): number {
  return a * b;
}

console.log(multiply(5, 10)); // 50
// console.log(multiply("Hello, ", "TypeScript!")); // Error: Argument of type 'string' is not assignable to parameter of type 'number'.
// console.log(multiply(5, "10")); // Error: Argument of type 'string' is not assignable to parameter of type 'number'.

//separator
console.log("--------------------------------------------------");

// primitive types
let isActive: boolean = true;
let age: number = 30;
let name: string = "John Doe";
console.log(`isActive: ${isActive}, age: ${age}, name: ${name}`);

const PI: number = 3.14;
console.log(`PI: ${PI}`);
// check type of PI
console.log(`Type of PI: ${typeof PI}`);

let piasString: string = PI.toString();
console.log(`PI as string: ${piasString}`);
console.log(`Type of PI as string: ${typeof piasString}`);

//string to number
let num: number = parseInt(piasString);
console.log(`String: ${piasString}, Number: ${num.toFixed(2)}`);
console.log(`Type of num: ${typeof num}`);

// after number conversion showing 3.oo instead of 3.14 because toFixed(2) rounds the number to 2 decimal places and 3.14 becomes 3.00 when rounded to 2 decimal places.
// fix issue by using toFixed(2) on the original number before converting it to string
let num2: number = parseFloat(piasString); // using type assertion to convert string back to number
console.log(`Original PI: ${PI}, Rounded PI: ${num2.toFixed(2)}`);
console.log(`Type of num2: ${typeof num2}`);

// array of numbers
let numbers: number[] = [1, 2, 3, 4, 5];
console.log(`Numbers: ${numbers.join(", ")}`);

// null and undefined
let customer: undefined;
console.log(`Customer: ${customer}`); // Customer: undefined

// this is proving undefined and null are different types in TypeScript.
// undefined is a type that represents the absence of a value,
// while null is a type that represents the intentional absence of any object value.
// In this case, customer is declared as undefined,
// which means it has not been assigned a value yet.
// On the other hand, customer2 is declared as null, which means
// it has been explicitly assigned the value of null.
let customerRole: null;
// console.log(`customerRole: ${customerRole}`); // Customer2: null

// assigning null value to customerRole
customerRole = null;
console.log(`customerRole after assignment: ${customerRole}`);

// check if customerRole is null or undefined
if (!customerRole) {
  console.log("customerRole is null or undefined");
}

//customer3 type annotation is missing,
// so it is inferred as any type, which can hold any value including undefined.
// Therefore, when we log customer3,
// it shows as undefined because it has not been assigned any value yet.
let customerRole1;
console.log(`customerRole1: ${customerRole1}`); // Customer3: undefined

// check customer and customerRole are equal or not
console.log(`Is customer equal to customerRole? ${customer === customerRole}`); // false

// check customer and customerRole1 are equal or not
console.log(
  `Is customer equal to customerRole1? ${customer === customerRole1}`,
); // true

// assign value to customerRole1
customerRole1 = "Admin";
console.log(`customerRole1 after assignment: ${customerRole1}`); // Admin

// check customer and customerRole1 are equal or not
console.log(
  `Is customer equal to customerRole1? ${customer === customerRole1}`,
); // false

// bigint type
// before bigint we can only represent numbers up to 2^53 - 1, which is 9007199254740991.
// before how we can define big numbers in JavaScript is by using the Number type,
// but it has a maximum safe integer limit of 2^53 - 1.
// provide example of big number without using bigint type
const safeInteger = Number.MAX_SAFE_INTEGER; // 9007199254740991
console.log(`Big number without BigInt: ${safeInteger}`); // 9007199254740991

// add 1 to the safe integer to show the issue with number type
console.log(`Safe integer + 1: ${safeInteger + 1}`); // 9007199254740992
console.log(`Safe integer + 20: ${safeInteger + 20}`); // 9007199254741012
// as you can see, adding 1 to the safe integer gives us 9007199254740992,
// which is correct, but adding 20 gives us 9007199254741012,
// which is incorrect because it exceeds the maximum safe integer limit.

let bigNumber: bigint = 9007199254740991n;
console.log(`Big number with BigInt: ${bigNumber}`); // 9007199254740991n

// add 1 to the big number to show that it can handle larger numbers
console.log(`Big number + 1: ${bigNumber + 1n}`); // 9007199254740992n
console.log(`Big number + 20: ${bigNumber + 20n}`); // 9007199254741011n

// using BigInt constructor to create big number
let bigNumber2: bigint = BigInt("12232334");

console.log(`Big number with BigInt constructor: ${bigNumber2}`); // 12232334n

// add 1 to the big number to show that it can handle larger numbers
console.log(`Big number2 + 1: ${bigNumber2 + 1n}`); // 12232335n
console.log(`Big number2 + 20: ${bigNumber2 + 20n}`); // 12232354n

// expression that evaluates big number also a big int by default
let bigNumber3 = bigNumber - bigNumber2; // 9007199254740992n
console.log(`Big number3: ${bigNumber3}`); // 9007199254740992n

// Symbol type
let id: symbol = Symbol();
console.log(`Symbol: ${id.toString()}`); // Symbol(id)

let user = {
  [id]: "1046113",
  name: "John Doe",
};

console.log(`User Name: ${user.name}`); // User Name: John Doe
//console.log(`User ID: ${user.id}`); // error: Property 'id' does not exist on type '{ [x: symbol]: string; name: string; }'.
// to access the symbol property, we need to use the symbol variable as the key
console.log(id); // Symbol() - this is the symbol value, it is unique and cannot be converted to string directly, we need to use toString() method to convert it to string
console.log(`User ID: ${user[id]}`); // User ID: 1046113

// symbol for private property
let user1 = {
  [id]: "1046114",
  name: "Jane Doe",
  getId: function () {
    return this[id];
  },
};

console.log(`User ID: ${user1.getId()}`); // User ID: 1046114

const sym1 = Symbol("sym1");
const sym2 = Symbol("sym2");

console.log(`Symbol 1: ${sym1.toString()}`); // Symbol(sym1)

console.log(`Symbol 2: ${sym2.toString()}`); // Symbol(sym2)

// check if sym1 and sym2 are equal
// console.log(`Is sym1 equal to sym2? ${sym1 === sym2}`); // false

let booleanValue: boolean;
booleanValue = typeof "Hello, World!" == "string";
console.log(`Is "Hello, World!" a string? ${booleanValue}`); // Is "Hello, World!" a string? true

//== vs ===
let str1: string = "5";
let str2: string = "5";

console.log(`str1 == str2: ${str1 == str2}`); // true
console.log(`str1 === str2: ${str1 === str2}`); // true

// why str1 == str2 is true and str1 === str2 is also true?
// because both str1 and str2 are of type string and have the same value "5",
// so both == and === will return true in this case.

str1 = "51";
str2 = "50";

console.log(`str1 == str2: ${str1 == str2}`); // false
console.log(`str1 === str2: ${str1 === str2}`); // false

console.log(`Is str1 equal to (==) str2? ${typeof str1 == typeof str2}`); // true
console.log(`Is str1 equal to(===) str2? ${typeof str1 === typeof str2}`); // true

// New TypeScript 5 feature: Type-Only Equality Operators
// type hierarchy in typescript is based on structural typing, which means that two types are considered equal if they have the same structure, regardless of their names.

// any type is a top type in TypeScript, which means that it can be assigned to any other type without causing a type error.

let name1: any = "John Doe"; // noImpleicitly typed as any as true in tsconfig.json

name1 = 12345; // no error because name is of type any
name1 = [1234];
name1 = { name: "John Doe" };
name1 = true;

// check if name1 is equal to string type using type-only equality operator
console.log(`Is name1 equal to string type? ${typeof name1 == "string"}`); // false
console.log(
  `Is name1 strictly equal to string type? ${typeof name1 === "string"}`,
); // false

let name2: string = "Jane Doe";

// check if name2 is equal to string type using type-only equality operator
console.log(`Is name2 equal to string type? ${typeof name2 == "string"}`); // true
console.log(
  `Is name2 strictly equal to string type? ${typeof name2 === "string"}`,
); // true

// unkown type is a top type in TypeScript, which means that it can be assigned to any other type without causing a type error, but it cannot be assigned to any other type without a type assertion or a type guard.
let value: unknown = "Hello, World!"; // value is of type unknown
// check if value is equal to string type using type-only equality operator
console.log(`Is value equal to string type? ${typeof value == "string"}`); // true
console.log(
  `Is value strictly equal to string type? ${typeof value === "string"}`,
); // true

// is Elgible to vote function using type-only equality operator to check if age is number type
function isEligibleToVote(age: unknown): boolean {
  if (typeof age == "number") {
    return age >= 18;
  } else {
    console.log("Age must be a number");
    return false;
  }
}

console.log(`Is 20 eligible to vote? ${isEligibleToVote(20)}`); // true
console.log(`Is "20" eligible to vote? ${isEligibleToVote("20")}`); // Age must be a number, false

// other JS Type

// Date, Array, Object, Function, Error, RegExp, Map, Set, WeakMap, WeakSet, Promise, etc.
// are also types in JavaScript and TypeScript.

// Type Aliases or Custom Types

// Declartion of type aliases for primitive types
type customString = string;
type customNumber = number;
type customBoolean = boolean;
type customSymbol = symbol;

// annotating variables with custom types
let myString: customString = "Hello, TypeScript!";
let myNumber: customNumber = 42;
let myBoolean: customBoolean = true;
let mySymbol: customSymbol = Symbol("mySymbol");

type customArray = number[];
type customObject = {
  name: string;
  age: number;
};

let myArray: customArray = [1, 2, 3, 4, 5];
let myObject: customObject = {
  name: "John Doe",
  age: 30,
};

console.log(`Customer Name: ${myArray}, Customer Email: ${myArray.join(", ")}`); // Customer Name: 1,2,3,4,5, Customer Email: 1,2,3,4,5
console.log(`Customer Name: ${myObject.name}, Customer Age: ${myObject.age}`); // Customer Name: John Doe, Customer Age: 30

type Customer = {
  name: string;
  email: string;
};

let customerObject: Customer = {
  name: "John Doe",
  email: "john.doe@example.com",
};

console.log(
  `Customer Name: ${customerObject.name}, Customer Email: ${customerObject.email}`,
);

// Duck Typing in TypeScript
// Duck typing is a concept in programming where the type or class of an object is
// determined by its behavior (methods and properties) rather than its explicit declaration.
// In TypeScript, this means that if an object has the necessary properties and methods,
// it can be treated as a certain type, even if it doesn't explicitly implement that type.
type Point = {
  x: number;
  y: number;
};

function printPoint(point: Point) {
  console.log(`Point coordinates: (${point.x}, ${point.y})`);
}

// union types (| operator)

type StringOrNumber = string | number;
type StrinOrNumberOrUndefined = string | number | undefined;
type NumberOrUndefined = number | undefined;
type DateOrUndefined = Date | undefined;

let value1: StringOrNumber = "Hello, TypeScript!";
let value2: StringOrNumber = 42;
console.log(`Value 1: ${value1}, Value 2: ${value2}`); // Value 1: Hello, TypeScript!, Value 2: 42

let value3: NumberOrUndefined = 100;
console.log(`Value 3: ${value3}`); // Value 3: 100

let value4: StrinOrNumberOrUndefined = "Hello, TypeScript!";
console.log(`Value 4: ${value4}`); // Value 4: Hello, TypeScript!

function printValue(input: unknown) {
  if (typeof input === "string") {
    console.log(`Input is a string: ${input}`);
  } else if (typeof input === "number") {
    console.log(`Input is a number: ${input}`);
  } else {
    console.log("Input is of unknown type");
  }
}

printValue("Hello, TypeScript!");
printValue(42);
printValue(true);

// intersection types   (& operator)
type Person = {
  name: string;
  age: number;
};
type Employee = {
  employeeId: number;
};

type EmployeePerson = Person & Employee;
let employeePerson: EmployeePerson = {
  name: "John Doe",
  age: 30,
  employeeId: 12345,
};

console.log(
  `Employee Name: ${employeePerson.name}, Employee Age: ${employeePerson.age}, Employee ID: ${employeePerson.employeeId}`,
); // Employee Name: John Doe, Employee Age: 30, Employee ID: 12345

// Conditional Types
type CustomeStringForCT = string;
type CustomeNumberForCT = number;
type CustomeDateForCT = Date;

type TrueString = CustomeStringForCT extends string ? "Yes" : "No";
type ConditionalNumber = CustomeNumberForCT extends number ? number : undefined;
type ConditionalDate = CustomeDateForCT extends Date ? Date : undefined;

let conditionalString: TrueString = "Yes";
let conditionalNumber: ConditionalNumber = 42;
let conditionalDate: ConditionalDate = new Date();

// check the conditional types
console.log(`Is CustomeStringForCT a string? ${conditionalString}`);
console.log(`Conditional Number: ${conditionalNumber}`); // Conditional Number: number
console.log(`Conditional Date: ${conditionalDate}`); // Conditional Date: Date

// add generic type parameter to the conditional type
type IsString<T> = T extends string ? "Yes" : "No";

type Test1 = IsString<string>;
type Test2 = IsString<number>;

let test1: Test1 = "Yes";
console.log(`Is string a string? ${test1}`); // Is string a string? Yes

let test2: Test2 = "No";
console.log(`Is number a string? ${test2}`); // Is number a string? No

// type hierarchy

type checkTypeHierarchy1 = any extends unknown ? true : false;
type checkTypeHierarchy2 = string extends any ? true : false;
type checkTypeHierarchy3 = null extends any ? true : false;
type checkTypeHierarchy4 = undefined extends void ? true : false;
type checkTypeHierarchy5 = [] extends object ? true : false;
type checkTypeHierarchy6 = {} extends object ? true : false;
type checkTypeHierarchy7 = Function extends object ? true : false;

// use all the checkTypeHierarchy types in a console log statement
let checkTypeHierarchy1: checkTypeHierarchy1 = true;
let checkTypeHierarchy2: checkTypeHierarchy2 = true;
let checkTypeHierarchy3: checkTypeHierarchy3 = true;
let checkTypeHierarchy4: checkTypeHierarchy4 = true;
let checkTypeHierarchy5: checkTypeHierarchy5 = true;
let checkTypeHierarchy6: checkTypeHierarchy6 = true;
let checkTypeHierarchy7: checkTypeHierarchy7 = true;

console.log(`Is any type a subtype of unknown type? ${checkTypeHierarchy1}`);
console.log(`Is string type a subtype of any type? ${checkTypeHierarchy2}`);
console.log(`Is null type a subtype of any type? ${checkTypeHierarchy3}`);
console.log(`Is undefined type a subtype of void type? ${checkTypeHierarchy4}`);
console.log(`Is array type a subtype of object type? ${checkTypeHierarchy5}`);
console.log(
  `Is object literal type a subtype of object type? ${checkTypeHierarchy6}`,
);
console.log(
  `Is function type a subtype of object type? ${checkTypeHierarchy7}`,
);

let checkTypeHierarchy123:
  | checkTypeHierarchy1
  | checkTypeHierarchy2
  | checkTypeHierarchy3 = true;
console.log(`Is any type a subtype of unknown type? ${checkTypeHierarchy123}`);
// Is any type a subtype of unknown type? Yes

// never type NeverType = never;
const throwError = (errorMessage: string): never => {
  throw new Error(errorMessage);
};

try {
  throwError("This is an error message");
} catch (error) {
  console.error(`Caught an error: ${(error as Error).message}`);
}   

let strings: string[] = ["Hello", "TypeScript", "World"];
let stringArrayasObj: object = ["Hello", "TypeScript", "World"];
console.log(`Strings: ${strings.join(", ")}`);  
console.log(`String as object: ${stringArrayasObj}`); // String as object: Hello,TypeScript,World


let myFucntion: Function = function (a: number, b: number): number {
  return a + b;
}

let myFucntionAsObj: Object = function (a: number, b: number): number {
  return a + b;
}

console.log(`My Function: ${myFucntion(5, 10)}`); // My Function: 15
console.log(`My Function as object: ${myFucntionAsObj}`); // My Function as object: function (a, b) { return a + b; }

// how to call myFucntionAsObj as a function
if (typeof myFucntionAsObj === "function") {
  console.log(`My Function as object called: ${myFucntionAsObj(5, 10)}`); // My Function as object called: 15       
} else {
  console.log("myFucntionAsObj is not a function");
}       

// type casting
let firstName = <any> "sankar"; // type assertion to any type
console.log(`First Name: ${firstName}`); // First Name: sankar

let lastName: string = "Doe" as any;
console.log(`Last Name: ${lastName}`); // Last Name: Doe

// user object from API
let userReponseObj = {
    name: "John Doe",
    age: 30,
};

type User = {
    name: string;
    age: number;
}

function fetchUserData(id: number){
    return userReponseObj as User; // simulating an API response   
}

const fetchedUserData = fetchUserData(12);
console.log(`Fetched User Name: ${fetchedUserData.name}, Fetched User Age: ${fetchedUserData.age}`); // Fetched User Name: John Doe, Fetched User Age: 30


Console.log("--------------------------Functions in TS -----------------------------");

// Defining a named function in TypeScript
function intro(name: string, age: number): string {
  return `My name is ${name} and I am ${age} years old`;
}

// Using a fucntion expression
const intro2 = function (name: string, age: number): string {
  return `My name is ${name} and I am ${age} years old`;
};

// Using the arrow function syntax
const intro3 = (name: string, age: number): string => {
  return `My name is ${name} and I am ${age} years old`;
};


// Functions often need optional params
// We can add optional params by using ? just like we do with objects, PAUSE AND PRACTICE
function intro(name: string, age: number, country?: string): string {
  if (country) {
    return `My name is ${name} and I am ${age} years old, I live in ${country}`;
  }
  return `My name is ${name} and I am ${age} years old`;
}

// TypeScript will throw an error if all defualt params are not added as arguments
// The error displays while you are programming and not at runtime
//! intro("John");
intro("Sankar", 32);

--------

  // Enum to represent the unit of age
// Using enum avoids magic strings and ensures type safety
enum AgeUnit {
  Years = "years",
  Months = "months",
}

// Person type definition
// Represents a person with name, age value, age unit, and country
type Person = {
  name: string;        // Person's name
  age: number;         // Age value (based on ageUnit)
  ageUnit: AgeUnit;    // Unit of age (Years or Months)
  country: string;     // Country of residence
};

// Sample person object
let person: Person = {
  name: "Sankar",
  age: 34,
  ageUnit: AgeUnit.Years,
  country: "India",
};

/**
 * Converts a person's age to months.
 *
 * Behavior:
 * - If age is in Years → converts to Months (age * 12)
 * - If already in Months → no change
 *
 * Note:
 * This function MUTATES the original object (not immutable).
 * In enterprise applications, consider returning a new object instead.
 */
function convertAgeToMonths(person: Person): Person {
  // Check if age is currently in years
  if (person.ageUnit === AgeUnit.Years) {
    // Convert years to months
    person.age = person.age * 12;

    // Update the age unit
    person.ageUnit = AgeUnit.Months;
  }

  // Return the updated person object
  return person;
}

// Execute conversion and print result
console.log(convertAgeToMonths(person));

// ----------------------

// Function call Signature

// Enum to represent age units
// Prevents use of hardcoded strings and improves type safety
enum AgeUnit {
  Years = "years",
  Months = "months",
}

// Function type definition for greeting
// Takes a greeting string and returns a formatted string
type GreetingFunction = (
  greeting: string /* additional parameters can be added later */
) => string;

// Person type definition
type Person = {
  name: string;              // Person's name
  age: number;               // Age value (based on ageUnit)
  ageUnit: AgeUnit;          // Unit of age (Years or Months)
  country: string;           // Country of residence
  // greet: Function;        // Avoid using generic Function type (not type-safe)
  greet: GreetingFunction;   // Strongly typed greeting function
};

// Creating a Person object
let person: Person = {
  name: "Sankar",
  age: 34,
  ageUnit: AgeUnit.Years,
  country: "India",

  // Implementation of greet function
  // Returns greeting message with person's name
  greet: (greeting) => {
    // Note: This uses the outer 'person' reference.
    // In larger systems, prefer using parameters or 'this' carefully.
    return `${greeting} ${person.name}`;
  },
};

/**
 * Converts age to months if it is currently in years.
 * 
 * Behavior:
 * - If ageUnit is Years → converts age to Months
 * - If already Months → no change
 * 
 * Note:
 * This function mutates the original object.
 * In enterprise applications, consider returning a new object (immutability).
 */
function convertAgeToMonths(person: Person): Person {
  // Check if age is in Years
  if (person.ageUnit === AgeUnit.Years) {
    // Convert years to months
    person.age = person.age * 12;

    // Update the age unit
    person.ageUnit = AgeUnit.Months;
  }

  // Return the updated person object
  return person;
}

// Convert age and print the updated object
console.log(convertAgeToMonths(person));

// Call greet function and print greeting message
console.log(person.greet("Hello"));

// -------------------Anonymous Function -------

// Array of student names
// TypeScript infers the type automatically as: string[]
const students = ["Alice", "Bob", "Mark"];

// Loop through the students array using map()
// Since 'students' is of type string[],
// TypeScript automatically infers the type of 'student' as string (Anonymous fn)
students.map((student) => {
  // 'student' is inferred as type: string
  console.log(student);
});

// The same type inference works when using a function expression
// (function keyword) instead of an arrow function (named Anonymous fn)
students.map(function (student) {
  // Here also, TypeScript infers 'student' as string
  // No need to explicitly write (student: string)
  console.log(student);
});
